// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'components/runners.dart';
import 'frb_generated.dart';
import 'game_providers/hoyoplay/proto.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'video_decoder.dart';

// These functions are ignored because they are not marked as `pub`: `convert_content`, `convert_game`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Initialize the backend (call on app startup)
Future<String> initBackend() => RustLib.instance.api.crateFfiInitBackend();

/// Get settings - returns struct directly!
Settings getSettings() => RustLib.instance.api.crateFfiGetSettings();

/// Get all games - returns Vec<Game> directly!
Future<List<Game>> getAllGames() => RustLib.instance.api.crateFfiGetAllGames();

/// Get game content - returns Content or None
Future<Content?> getGameContent(
        {required String gameId, required String biz}) =>
    RustLib.instance.api.crateFfiGetGameContent(gameId: gameId, biz: biz);

/// Check if a game is installed
bool isGameInstalled({required String gameId, required String biz}) =>
    RustLib.instance.api.crateFfiIsGameInstalled(gameId: gameId, biz: biz);

/// Get download progress - returns DownloadProgress or None
DownloadProgress? getDownloadProgress({required String gameId}) =>
    RustLib.instance.api.crateFfiGetDownloadProgress(gameId: gameId);

/// Get data directory path
String getDataPath() => RustLib.instance.api.crateFfiGetDataPath();

/// Get config file path
String getConfigPath() => RustLib.instance.api.crateFfiGetConfigPath();

/// Install/download a game - returns "ok" or error message
Future<String> installGame({required String gameId, required String biz}) =>
    RustLib.instance.api.crateFfiInstallGame(gameId: gameId, biz: biz);

/// Launch an installed game - returns "ok" or error message
Future<String> launchGame({required String gameId}) =>
    RustLib.instance.api.crateFfiLaunchGame(gameId: gameId);

/// Get available runners - returns Vec<AvailableRunner>
List<AvailableRunner> getAvailableRunners() =>
    RustLib.instance.api.crateFfiGetAvailableRunners();

/// Get available components - returns Vec<AvailableComponent>
List<AvailableComponent> getAvailableComponents() =>
    RustLib.instance.api.crateFfiGetAvailableComponents();

/// Install a runner by name - returns "ok" or error message
Future<String> installRunner({required String runnerName}) =>
    RustLib.instance.api.crateFfiInstallRunner(runnerName: runnerName);

/// Delete a runner by name - returns "ok" or error message
Future<String> deleteRunner({required String runnerName}) =>
    RustLib.instance.api.crateFfiDeleteRunner(runnerName: runnerName);

/// Install UMU launcher component - returns "ok" or error message
Future<String> installUmuLauncher() =>
    RustLib.instance.api.crateFfiInstallUmuLauncher();

/// Install Jadeite component - returns "ok" or error message
Future<String> installJadeite() =>
    RustLib.instance.api.crateFfiInstallJadeite();

/// Delete UMU launcher component - returns "ok" or error message
Future<String> deleteUmuLauncher() =>
    RustLib.instance.api.crateFfiDeleteUmuLauncher();

/// Delete Jadeite component - returns "ok" or error message
Future<String> deleteJadeite() => RustLib.instance.api.crateFfiDeleteJadeite();

/// Stream video frames from a URL
Stream<VideoFrame> streamVideoFrames({required String url}) =>
    RustLib.instance.api.crateFfiStreamVideoFrames(url: url);

/// Available component information
class AvailableComponent {
  final String name;
  final String displayName;
  final bool isInstalled;

  const AvailableComponent({
    required this.name,
    required this.displayName,
    required this.isInstalled,
  });

  @override
  int get hashCode =>
      name.hashCode ^ displayName.hashCode ^ isInstalled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AvailableComponent &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          displayName == other.displayName &&
          isInstalled == other.isInstalled;
}

/// Download progress information
class DownloadProgress {
  final BigInt downloaded;
  final BigInt total;
  final double mbPerSecond;
  final BigInt partIndex;
  final BigInt partsTotal;
  final String status;
  final bool isBusy;

  const DownloadProgress({
    required this.downloaded,
    required this.total,
    required this.mbPerSecond,
    required this.partIndex,
    required this.partsTotal,
    required this.status,
    required this.isBusy,
  });

  @override
  int get hashCode =>
      downloaded.hashCode ^
      total.hashCode ^
      mbPerSecond.hashCode ^
      partIndex.hashCode ^
      partsTotal.hashCode ^
      status.hashCode ^
      isBusy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadProgress &&
          runtimeType == other.runtimeType &&
          downloaded == other.downloaded &&
          total == other.total &&
          mbPerSecond == other.mbPerSecond &&
          partIndex == other.partIndex &&
          partsTotal == other.partsTotal &&
          status == other.status &&
          isBusy == other.isBusy;
}

/// Settings paths
class Settings {
  final String wineprefixesDirectory;
  final String componentsDirectory;
  final String tempDirectory;
  final String cacheDirectory;

  const Settings({
    required this.wineprefixesDirectory,
    required this.componentsDirectory,
    required this.tempDirectory,
    required this.cacheDirectory,
  });

  @override
  int get hashCode =>
      wineprefixesDirectory.hashCode ^
      componentsDirectory.hashCode ^
      tempDirectory.hashCode ^
      cacheDirectory.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Settings &&
          runtimeType == other.runtimeType &&
          wineprefixesDirectory == other.wineprefixesDirectory &&
          componentsDirectory == other.componentsDirectory &&
          tempDirectory == other.tempDirectory &&
          cacheDirectory == other.cacheDirectory;
}
