// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'components/runners.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'ffi.dart';
import 'frb_generated.dart';
import 'game_providers/hoyoplay/proto.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'video_decoder.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_GamePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGamePtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_SocialMediaPtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMediaPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Game
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
          dynamic raw);

  @protected
  SocialMedia
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMedia(
          dynamic raw);

  @protected
  Game
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
          dynamic raw);

  @protected
  SocialMedia
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMedia(
          dynamic raw);

  @protected
  RustStreamSink<VideoFrame> dco_decode_StreamSink_video_frame_Dco(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AvailableComponent dco_decode_available_component(dynamic raw);

  @protected
  AvailableRunner dco_decode_available_runner(dynamic raw);

  @protected
  Banner dco_decode_banner(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  Content dco_decode_box_autoadd_content(dynamic raw);

  @protected
  DownloadProgress dco_decode_box_autoadd_download_progress(dynamic raw);

  @protected
  Content dco_decode_content(dynamic raw);

  @protected
  DownloadProgress dco_decode_download_progress(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  GameInfo dco_decode_game_info(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImageLink dco_decode_image_link(dynamic raw);

  @protected
  List<Game>
      dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
          dynamic raw);

  @protected
  List<SocialMedia>
      dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMedia(
          dynamic raw);

  @protected
  List<AvailableComponent> dco_decode_list_available_component(dynamic raw);

  @protected
  List<AvailableRunner> dco_decode_list_available_runner(dynamic raw);

  @protected
  List<Banner> dco_decode_list_banner(dynamic raw);

  @protected
  List<Post> dco_decode_list_post(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  Content? dco_decode_opt_box_autoadd_content(dynamic raw);

  @protected
  DownloadProgress? dco_decode_opt_box_autoadd_download_progress(dynamic raw);

  @protected
  Post dco_decode_post(dynamic raw);

  @protected
  RunnerType dco_decode_runner_type(dynamic raw);

  @protected
  Settings dco_decode_settings(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VideoFrame dco_decode_video_frame(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Game
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
          SseDeserializer deserializer);

  @protected
  SocialMedia
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMedia(
          SseDeserializer deserializer);

  @protected
  Game
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
          SseDeserializer deserializer);

  @protected
  SocialMedia
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMedia(
          SseDeserializer deserializer);

  @protected
  RustStreamSink<VideoFrame> sse_decode_StreamSink_video_frame_Dco(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AvailableComponent sse_decode_available_component(
      SseDeserializer deserializer);

  @protected
  AvailableRunner sse_decode_available_runner(SseDeserializer deserializer);

  @protected
  Banner sse_decode_banner(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  Content sse_decode_box_autoadd_content(SseDeserializer deserializer);

  @protected
  DownloadProgress sse_decode_box_autoadd_download_progress(
      SseDeserializer deserializer);

  @protected
  Content sse_decode_content(SseDeserializer deserializer);

  @protected
  DownloadProgress sse_decode_download_progress(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  GameInfo sse_decode_game_info(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImageLink sse_decode_image_link(SseDeserializer deserializer);

  @protected
  List<Game>
      sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
          SseDeserializer deserializer);

  @protected
  List<SocialMedia>
      sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMedia(
          SseDeserializer deserializer);

  @protected
  List<AvailableComponent> sse_decode_list_available_component(
      SseDeserializer deserializer);

  @protected
  List<AvailableRunner> sse_decode_list_available_runner(
      SseDeserializer deserializer);

  @protected
  List<Banner> sse_decode_list_banner(SseDeserializer deserializer);

  @protected
  List<Post> sse_decode_list_post(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  Content? sse_decode_opt_box_autoadd_content(SseDeserializer deserializer);

  @protected
  DownloadProgress? sse_decode_opt_box_autoadd_download_progress(
      SseDeserializer deserializer);

  @protected
  Post sse_decode_post(SseDeserializer deserializer);

  @protected
  RunnerType sse_decode_runner_type(SseDeserializer deserializer);

  @protected
  Settings sse_decode_settings(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VideoFrame sse_decode_video_frame(SseDeserializer deserializer);

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_AnyhowException(
      AnyhowException raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict>
      cst_encode_StreamSink_video_frame_Dco(RustStreamSink<VideoFrame> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_String(raw.setupAndSerialize(
        codec: DcoCodec(
      decodeSuccessData: dco_decode_video_frame,
      decodeErrorData: dco_decode_AnyhowException,
    )));
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_cst_content> cst_encode_box_autoadd_content(Content raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_content();
    cst_api_fill_to_wire_content(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_download_progress>
      cst_encode_box_autoadd_download_progress(DownloadProgress raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_download_progress();
    cst_api_fill_to_wire_download_progress(raw, ptr.ref);
    return ptr;
  }

  @protected
  int cst_encode_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toInt();
  }

  @protected
  ffi.Pointer<
          wire_cst_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame>
      cst_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
          List<Game> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire
        .cst_new_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
            raw.length);
    for (var i = 0; i < raw.length; ++i) {
      ans.ref.ptr[i] =
          cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
              raw[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<
          wire_cst_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMedia>
      cst_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMedia(
          List<SocialMedia> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire
        .cst_new_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMedia(
            raw.length);
    for (var i = 0; i < raw.length; ++i) {
      ans.ref.ptr[i] =
          cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMedia(
              raw[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_available_component>
      cst_encode_list_available_component(List<AvailableComponent> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_available_component(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_available_component(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_available_runner> cst_encode_list_available_runner(
      List<AvailableRunner> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_available_runner(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_available_runner(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_banner> cst_encode_list_banner(List<Banner> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_banner(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_banner(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_post> cst_encode_list_post(List<Post> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_post(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_post(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(
      Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_content> cst_encode_opt_box_autoadd_content(
      Content? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_content(raw);
  }

  @protected
  ffi.Pointer<wire_cst_download_progress>
      cst_encode_opt_box_autoadd_download_progress(DownloadProgress? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? ffi.nullptr
        : cst_encode_box_autoadd_download_progress(raw);
  }

  @protected
  int cst_encode_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toSigned(64).toInt();
  }

  @protected
  int cst_encode_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toSigned(64).toInt();
  }

  @protected
  void cst_api_fill_to_wire_available_component(
      AvailableComponent apiObj, wire_cst_available_component wireObj) {
    wireObj.name = cst_encode_String(apiObj.name);
    wireObj.display_name = cst_encode_String(apiObj.displayName);
    wireObj.is_installed = cst_encode_bool(apiObj.isInstalled);
  }

  @protected
  void cst_api_fill_to_wire_available_runner(
      AvailableRunner apiObj, wire_cst_available_runner wireObj) {
    wireObj.name = cst_encode_String(apiObj.name);
    wireObj.display_name = cst_encode_String(apiObj.displayName);
    wireObj.runner_type = cst_encode_runner_type(apiObj.runnerType);
    wireObj.version = cst_encode_String(apiObj.version);
    wireObj.download_url = cst_encode_String(apiObj.downloadUrl);
    wireObj.folder_name = cst_encode_String(apiObj.folderName);
  }

  @protected
  void cst_api_fill_to_wire_banner(Banner apiObj, wire_cst_banner wireObj) {
    wireObj.id = cst_encode_String(apiObj.id);
    cst_api_fill_to_wire_image_link(apiObj.image, wireObj.image);
    wireObj.i18n_identifier = cst_encode_String(apiObj.i18NIdentifier);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_content(
      Content apiObj, ffi.Pointer<wire_cst_content> wireObj) {
    cst_api_fill_to_wire_content(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_download_progress(
      DownloadProgress apiObj,
      ffi.Pointer<wire_cst_download_progress> wireObj) {
    cst_api_fill_to_wire_download_progress(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_content(Content apiObj, wire_cst_content wireObj) {
    cst_api_fill_to_wire_game_info(apiObj.game, wireObj.game);
    wireObj.language = cst_encode_String(apiObj.language);
    wireObj.banners = cst_encode_list_banner(apiObj.banners);
    wireObj.posts = cst_encode_list_post(apiObj.posts);
    wireObj.social_media_list =
        cst_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMedia(
            apiObj.socialMediaList);
  }

  @protected
  void cst_api_fill_to_wire_download_progress(
      DownloadProgress apiObj, wire_cst_download_progress wireObj) {
    wireObj.downloaded = cst_encode_u_64(apiObj.downloaded);
    wireObj.total = cst_encode_u_64(apiObj.total);
    wireObj.mb_per_second = cst_encode_f_32(apiObj.mbPerSecond);
    wireObj.part_index = cst_encode_usize(apiObj.partIndex);
    wireObj.parts_total = cst_encode_usize(apiObj.partsTotal);
    wireObj.status = cst_encode_String(apiObj.status);
    wireObj.is_busy = cst_encode_bool(apiObj.isBusy);
  }

  @protected
  void cst_api_fill_to_wire_game_info(
      GameInfo apiObj, wire_cst_game_info wireObj) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.biz = cst_encode_String(apiObj.biz);
  }

  @protected
  void cst_api_fill_to_wire_image_link(
      ImageLink apiObj, wire_cst_image_link wireObj) {
    wireObj.url = cst_encode_String(apiObj.url);
    wireObj.link = cst_encode_String(apiObj.link);
    wireObj.login_state_in_link = cst_encode_bool(apiObj.loginStateInLink);
  }

  @protected
  void cst_api_fill_to_wire_post(Post apiObj, wire_cst_post wireObj) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.post_type = cst_encode_String(apiObj.postType);
    wireObj.title = cst_encode_String(apiObj.title);
    wireObj.link = cst_encode_String(apiObj.link);
    wireObj.date = cst_encode_String(apiObj.date);
    wireObj.login_state_in_link = cst_encode_bool(apiObj.loginStateInLink);
    wireObj.i18n_identifier = cst_encode_String(apiObj.i18NIdentifier);
  }

  @protected
  void cst_api_fill_to_wire_settings(
      Settings apiObj, wire_cst_settings wireObj) {
    wireObj.wineprefixes_directory =
        cst_encode_String(apiObj.wineprefixesDirectory);
    wireObj.components_directory =
        cst_encode_String(apiObj.componentsDirectory);
    wireObj.temp_directory = cst_encode_String(apiObj.tempDirectory);
    wireObj.cache_directory = cst_encode_String(apiObj.cacheDirectory);
  }

  @protected
  void cst_api_fill_to_wire_video_frame(
      VideoFrame apiObj, wire_cst_video_frame wireObj) {
    wireObj.data = cst_encode_list_prim_u_8_strict(apiObj.data);
    wireObj.width = cst_encode_u_32(apiObj.width);
    wireObj.height = cst_encode_u_32(apiObj.height);
    wireObj.timestamp_ms = cst_encode_i_64(apiObj.timestampMs);
  }

  @protected
  int cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
      Game raw);

  @protected
  int cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMedia(
      SocialMedia raw);

  @protected
  int cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
      Game raw);

  @protected
  int cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMedia(
      SocialMedia raw);

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  double cst_encode_f_32(double raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_runner_type(RunnerType raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
          Game self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMedia(
          SocialMedia self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
          Game self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMedia(
          SocialMedia self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_video_frame_Dco(
      RustStreamSink<VideoFrame> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_available_component(
      AvailableComponent self, SseSerializer serializer);

  @protected
  void sse_encode_available_runner(
      AvailableRunner self, SseSerializer serializer);

  @protected
  void sse_encode_banner(Banner self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_content(Content self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_download_progress(
      DownloadProgress self, SseSerializer serializer);

  @protected
  void sse_encode_content(Content self, SseSerializer serializer);

  @protected
  void sse_encode_download_progress(
      DownloadProgress self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_game_info(GameInfo self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_image_link(ImageLink self, SseSerializer serializer);

  @protected
  void
      sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
          List<Game> self, SseSerializer serializer);

  @protected
  void
      sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMedia(
          List<SocialMedia> self, SseSerializer serializer);

  @protected
  void sse_encode_list_available_component(
      List<AvailableComponent> self, SseSerializer serializer);

  @protected
  void sse_encode_list_available_runner(
      List<AvailableRunner> self, SseSerializer serializer);

  @protected
  void sse_encode_list_banner(List<Banner> self, SseSerializer serializer);

  @protected
  void sse_encode_list_post(List<Post> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_content(
      Content? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_download_progress(
      DownloadProgress? self, SseSerializer serializer);

  @protected
  void sse_encode_post(Post self, SseSerializer serializer);

  @protected
  void sse_encode_runner_type(RunnerType self, SseSerializer serializer);

  @protected
  void sse_encode_settings(Settings self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_video_frame(VideoFrame self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// generated by flutter_rust_bridge
class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustLibWire.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void store_dart_post_cobject(
    DartPostCObjectFnType ptr,
  ) {
    return _store_dart_post_cobject(
      ptr,
    );
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
          'store_dart_post_cobject');
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  void wire__crate__ffi__delete_jadeite(
    int port_,
  ) {
    return _wire__crate__ffi__delete_jadeite(
      port_,
    );
  }

  late final _wire__crate__ffi__delete_jadeitePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'frbgen_elysia_wire__crate__ffi__delete_jadeite');
  late final _wire__crate__ffi__delete_jadeite =
      _wire__crate__ffi__delete_jadeitePtr.asFunction<void Function(int)>();

  void wire__crate__ffi__delete_runner(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> runner_name,
  ) {
    return _wire__crate__ffi__delete_runner(
      port_,
      runner_name,
    );
  }

  late final _wire__crate__ffi__delete_runnerPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_elysia_wire__crate__ffi__delete_runner');
  late final _wire__crate__ffi__delete_runner =
      _wire__crate__ffi__delete_runnerPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__ffi__delete_umu_launcher(
    int port_,
  ) {
    return _wire__crate__ffi__delete_umu_launcher(
      port_,
    );
  }

  late final _wire__crate__ffi__delete_umu_launcherPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'frbgen_elysia_wire__crate__ffi__delete_umu_launcher');
  late final _wire__crate__ffi__delete_umu_launcher =
      _wire__crate__ffi__delete_umu_launcherPtr
          .asFunction<void Function(int)>();

  void wire__crate__ffi__get_all_games(
    int port_,
  ) {
    return _wire__crate__ffi__get_all_games(
      port_,
    );
  }

  late final _wire__crate__ffi__get_all_gamesPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'frbgen_elysia_wire__crate__ffi__get_all_games');
  late final _wire__crate__ffi__get_all_games =
      _wire__crate__ffi__get_all_gamesPtr.asFunction<void Function(int)>();

  WireSyncRust2DartDco wire__crate__ffi__get_available_components() {
    return _wire__crate__ffi__get_available_components();
  }

  late final _wire__crate__ffi__get_available_componentsPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
          'frbgen_elysia_wire__crate__ffi__get_available_components');
  late final _wire__crate__ffi__get_available_components =
      _wire__crate__ffi__get_available_componentsPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__ffi__get_available_runners() {
    return _wire__crate__ffi__get_available_runners();
  }

  late final _wire__crate__ffi__get_available_runnersPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
          'frbgen_elysia_wire__crate__ffi__get_available_runners');
  late final _wire__crate__ffi__get_available_runners =
      _wire__crate__ffi__get_available_runnersPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__ffi__get_config_path() {
    return _wire__crate__ffi__get_config_path();
  }

  late final _wire__crate__ffi__get_config_pathPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
          'frbgen_elysia_wire__crate__ffi__get_config_path');
  late final _wire__crate__ffi__get_config_path =
      _wire__crate__ffi__get_config_pathPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__ffi__get_data_path() {
    return _wire__crate__ffi__get_data_path();
  }

  late final _wire__crate__ffi__get_data_pathPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
          'frbgen_elysia_wire__crate__ffi__get_data_path');
  late final _wire__crate__ffi__get_data_path =
      _wire__crate__ffi__get_data_pathPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__ffi__get_download_progress(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> game_id,
  ) {
    return _wire__crate__ffi__get_download_progress(
      game_id,
    );
  }

  late final _wire__crate__ffi__get_download_progressPtr = _lookup<
          ffi.NativeFunction<
              WireSyncRust2DartDco Function(
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_elysia_wire__crate__ffi__get_download_progress');
  late final _wire__crate__ffi__get_download_progress =
      _wire__crate__ffi__get_download_progressPtr.asFunction<
          WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__ffi__get_game_content(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> game_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> biz,
  ) {
    return _wire__crate__ffi__get_game_content(
      port_,
      game_id,
      biz,
    );
  }

  late final _wire__crate__ffi__get_game_contentPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_elysia_wire__crate__ffi__get_game_content');
  late final _wire__crate__ffi__get_game_content =
      _wire__crate__ffi__get_game_contentPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  WireSyncRust2DartDco wire__crate__ffi__get_settings() {
    return _wire__crate__ffi__get_settings();
  }

  late final _wire__crate__ffi__get_settingsPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
          'frbgen_elysia_wire__crate__ffi__get_settings');
  late final _wire__crate__ffi__get_settings =
      _wire__crate__ffi__get_settingsPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  void wire__crate__ffi__init_backend(
    int port_,
  ) {
    return _wire__crate__ffi__init_backend(
      port_,
    );
  }

  late final _wire__crate__ffi__init_backendPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'frbgen_elysia_wire__crate__ffi__init_backend');
  late final _wire__crate__ffi__init_backend =
      _wire__crate__ffi__init_backendPtr.asFunction<void Function(int)>();

  void wire__crate__ffi__install_game(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> _game_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> _biz,
  ) {
    return _wire__crate__ffi__install_game(
      port_,
      _game_id,
      _biz,
    );
  }

  late final _wire__crate__ffi__install_gamePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_elysia_wire__crate__ffi__install_game');
  late final _wire__crate__ffi__install_game =
      _wire__crate__ffi__install_gamePtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__ffi__install_jadeite(
    int port_,
  ) {
    return _wire__crate__ffi__install_jadeite(
      port_,
    );
  }

  late final _wire__crate__ffi__install_jadeitePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'frbgen_elysia_wire__crate__ffi__install_jadeite');
  late final _wire__crate__ffi__install_jadeite =
      _wire__crate__ffi__install_jadeitePtr.asFunction<void Function(int)>();

  void wire__crate__ffi__install_runner(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> runner_name,
  ) {
    return _wire__crate__ffi__install_runner(
      port_,
      runner_name,
    );
  }

  late final _wire__crate__ffi__install_runnerPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_elysia_wire__crate__ffi__install_runner');
  late final _wire__crate__ffi__install_runner =
      _wire__crate__ffi__install_runnerPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__ffi__install_umu_launcher(
    int port_,
  ) {
    return _wire__crate__ffi__install_umu_launcher(
      port_,
    );
  }

  late final _wire__crate__ffi__install_umu_launcherPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'frbgen_elysia_wire__crate__ffi__install_umu_launcher');
  late final _wire__crate__ffi__install_umu_launcher =
      _wire__crate__ffi__install_umu_launcherPtr
          .asFunction<void Function(int)>();

  WireSyncRust2DartDco wire__crate__ffi__is_game_installed(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> game_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> biz,
  ) {
    return _wire__crate__ffi__is_game_installed(
      game_id,
      biz,
    );
  }

  late final _wire__crate__ffi__is_game_installedPtr = _lookup<
          ffi.NativeFunction<
              WireSyncRust2DartDco Function(
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_elysia_wire__crate__ffi__is_game_installed');
  late final _wire__crate__ffi__is_game_installed =
      _wire__crate__ffi__is_game_installedPtr.asFunction<
          WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__ffi__launch_game(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> _game_id,
  ) {
    return _wire__crate__ffi__launch_game(
      port_,
      _game_id,
    );
  }

  late final _wire__crate__ffi__launch_gamePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_elysia_wire__crate__ffi__launch_game');
  late final _wire__crate__ffi__launch_game =
      _wire__crate__ffi__launch_gamePtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__ffi__stream_video_frames(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> url,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> sink,
  ) {
    return _wire__crate__ffi__stream_video_frames(
      port_,
      url,
      sink,
    );
  }

  late final _wire__crate__ffi__stream_video_framesPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_elysia_wire__crate__ffi__stream_video_frames');
  late final _wire__crate__ffi__stream_video_frames =
      _wire__crate__ffi__stream_video_framesPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGamePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_elysia_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGamePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGamePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_elysia_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGamePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMedia(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMedia(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMediaPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_elysia_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMedia');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMedia =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMediaPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMedia(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMedia(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMediaPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_elysia_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMedia');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMedia =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMediaPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<wire_cst_content> cst_new_box_autoadd_content() {
    return _cst_new_box_autoadd_content();
  }

  late final _cst_new_box_autoadd_contentPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_content> Function()>>(
          'frbgen_elysia_cst_new_box_autoadd_content');
  late final _cst_new_box_autoadd_content = _cst_new_box_autoadd_contentPtr
      .asFunction<ffi.Pointer<wire_cst_content> Function()>();

  ffi.Pointer<wire_cst_download_progress>
      cst_new_box_autoadd_download_progress() {
    return _cst_new_box_autoadd_download_progress();
  }

  late final _cst_new_box_autoadd_download_progressPtr = _lookup<
          ffi
          .NativeFunction<ffi.Pointer<wire_cst_download_progress> Function()>>(
      'frbgen_elysia_cst_new_box_autoadd_download_progress');
  late final _cst_new_box_autoadd_download_progress =
      _cst_new_box_autoadd_download_progressPtr
          .asFunction<ffi.Pointer<wire_cst_download_progress> Function()>();

  ffi.Pointer<
          wire_cst_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame>
      cst_new_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
    int len,
  ) {
    return _cst_new_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
      len,
    );
  }

  late final _cst_new_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGamePtr =
      _lookup<
              ffi.NativeFunction<
                  ffi.Pointer<
                          wire_cst_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame>
                      Function(ffi.Int32)>>(
          'frbgen_elysia_cst_new_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame');
  late final _cst_new_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame =
      _cst_new_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGamePtr
          .asFunction<
              ffi.Pointer<
                      wire_cst_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame>
                  Function(int)>();

  ffi.Pointer<
          wire_cst_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMedia>
      cst_new_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMedia(
    int len,
  ) {
    return _cst_new_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMedia(
      len,
    );
  }

  late final _cst_new_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMediaPtr =
      _lookup<
              ffi.NativeFunction<
                  ffi.Pointer<
                          wire_cst_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMedia>
                      Function(ffi.Int32)>>(
          'frbgen_elysia_cst_new_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMedia');
  late final _cst_new_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMedia =
      _cst_new_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMediaPtr
          .asFunction<
              ffi.Pointer<
                      wire_cst_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMedia>
                  Function(int)>();

  ffi.Pointer<wire_cst_list_available_component>
      cst_new_list_available_component(
    int len,
  ) {
    return _cst_new_list_available_component(
      len,
    );
  }

  late final _cst_new_list_available_componentPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_available_component> Function(
              ffi.Int32)>>('frbgen_elysia_cst_new_list_available_component');
  late final _cst_new_list_available_component =
      _cst_new_list_available_componentPtr.asFunction<
          ffi.Pointer<wire_cst_list_available_component> Function(int)>();

  ffi.Pointer<wire_cst_list_available_runner> cst_new_list_available_runner(
    int len,
  ) {
    return _cst_new_list_available_runner(
      len,
    );
  }

  late final _cst_new_list_available_runnerPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_available_runner> Function(
              ffi.Int32)>>('frbgen_elysia_cst_new_list_available_runner');
  late final _cst_new_list_available_runner = _cst_new_list_available_runnerPtr
      .asFunction<ffi.Pointer<wire_cst_list_available_runner> Function(int)>();

  ffi.Pointer<wire_cst_list_banner> cst_new_list_banner(
    int len,
  ) {
    return _cst_new_list_banner(
      len,
    );
  }

  late final _cst_new_list_bannerPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_banner> Function(
              ffi.Int32)>>('frbgen_elysia_cst_new_list_banner');
  late final _cst_new_list_banner = _cst_new_list_bannerPtr
      .asFunction<ffi.Pointer<wire_cst_list_banner> Function(int)>();

  ffi.Pointer<wire_cst_list_post> cst_new_list_post(
    int len,
  ) {
    return _cst_new_list_post(
      len,
    );
  }

  late final _cst_new_list_postPtr = _lookup<
          ffi
          .NativeFunction<ffi.Pointer<wire_cst_list_post> Function(ffi.Int32)>>(
      'frbgen_elysia_cst_new_list_post');
  late final _cst_new_list_post = _cst_new_list_postPtr
      .asFunction<ffi.Pointer<wire_cst_list_post> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_8_strict(
      len,
    );
  }

  late final _cst_new_list_prim_u_8_strictPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(
              ffi.Int32)>>('frbgen_elysia_cst_new_list_prim_u_8_strict');
  late final _cst_new_list_prim_u_8_strict = _cst_new_list_prim_u_8_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
          'dummy_method_to_enforce_bundling');
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();
}

typedef DartPostCObjectFnType
    = ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnTypeFunction>>;
typedef DartPostCObjectFnTypeFunction = ffi.Bool Function(
    DartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartDartPostCObjectFnTypeFunction = bool Function(
    DartDartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartPort = ffi.Int64;
typedef DartDartPort = int;

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_game_info extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> biz;
}

final class wire_cst_image_link extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> url;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> link;

  @ffi.Bool()
  external bool login_state_in_link;
}

final class wire_cst_banner extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external wire_cst_image_link image;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> i18n_identifier;
}

final class wire_cst_list_banner extends ffi.Struct {
  external ffi.Pointer<wire_cst_banner> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_post extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> post_type;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> title;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> link;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> date;

  @ffi.Bool()
  external bool login_state_in_link;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> i18n_identifier;
}

final class wire_cst_list_post extends ffi.Struct {
  external ffi.Pointer<wire_cst_post> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMedia
    extends ffi.Struct {
  external ffi.Pointer<ffi.UintPtr> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_content extends ffi.Struct {
  external wire_cst_game_info game;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> language;

  external ffi.Pointer<wire_cst_list_banner> banners;

  external ffi.Pointer<wire_cst_list_post> posts;

  external ffi.Pointer<
          wire_cst_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSocialMedia>
      social_media_list;
}

final class wire_cst_download_progress extends ffi.Struct {
  @ffi.Uint64()
  external int downloaded;

  @ffi.Uint64()
  external int total;

  @ffi.Float()
  external double mb_per_second;

  @ffi.UintPtr()
  external int part_index;

  @ffi.UintPtr()
  external int parts_total;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> status;

  @ffi.Bool()
  external bool is_busy;
}

final class wire_cst_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame
    extends ffi.Struct {
  external ffi.Pointer<ffi.UintPtr> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_available_component extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> name;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> display_name;

  @ffi.Bool()
  external bool is_installed;
}

final class wire_cst_list_available_component extends ffi.Struct {
  external ffi.Pointer<wire_cst_available_component> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_available_runner extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> name;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> display_name;

  @ffi.Int32()
  external int runner_type;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> version;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> download_url;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> folder_name;
}

final class wire_cst_list_available_runner extends ffi.Struct {
  external ffi.Pointer<wire_cst_available_runner> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_settings extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> wineprefixes_directory;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> components_directory;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> temp_directory;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> cache_directory;
}

final class wire_cst_video_frame extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> data;

  @ffi.Uint32()
  external int width;

  @ffi.Uint32()
  external int height;

  @ffi.Int64()
  external int timestamp_ms;
}
