// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Video frame data
class VideoFrame {
  /// RGBA image data
  final Uint8List data;

  /// Image width
  final int width;

  /// Image height
  final int height;

  /// Frame timestamp in milliseconds
  final PlatformInt64 timestampMs;

  const VideoFrame({
    required this.data,
    required this.width,
    required this.height,
    required this.timestampMs,
  });

  @override
  int get hashCode =>
      data.hashCode ^ width.hashCode ^ height.hashCode ^ timestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoFrame &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          width == other.width &&
          height == other.height &&
          timestampMs == other.timestampMs;
}
