// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `content_to_dto`, `game_to_dto`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BannerDto`, `ContentDto`, `DownloadProgressDto`, `GameDto`, `PostDto`, `SettingsDto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Initialize the backend (call on app startup)
String initBackend() => RustLib.instance.api.crateApiInitBackend();

/// Get settings as JSON
String getSettingsJson() => RustLib.instance.api.crateApiGetSettingsJson();

/// Get all games as JSON array
Future<String> getAllGamesJson() =>
    RustLib.instance.api.crateApiGetAllGamesJson();

/// Get game content as JSON
Future<String> getGameContentJson({
  required String gameId,
  required String biz,
}) => RustLib.instance.api.crateApiGetGameContentJson(gameId: gameId, biz: biz);

/// Check if a game is installed
bool isGameInstalled({required String gameId, required String biz}) =>
    RustLib.instance.api.crateApiIsGameInstalled(gameId: gameId, biz: biz);

/// Get download progress as JSON (returns "null" if no download in progress)
String getDownloadProgressJson({required String gameId}) =>
    RustLib.instance.api.crateApiGetDownloadProgressJson(gameId: gameId);

/// Get data directory path
String getDataPath() => RustLib.instance.api.crateApiGetDataPath();

/// Get config file path
String getConfigPath() => RustLib.instance.api.crateApiGetConfigPath();
