// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `content_to_dto`, `game_to_dto`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AvailableComponentDto`, `AvailableRunnerDto`, `BannerDto`, `ContentDto`, `DownloadProgressDto`, `GameDto`, `PostDto`, `SettingsDto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Initialize the backend (call on app startup)
String initBackend() => RustLib.instance.api.crateApiInitBackend();

/// Get settings as JSON
String getSettingsJson() => RustLib.instance.api.crateApiGetSettingsJson();

/// Get all games as JSON array
Future<String> getAllGamesJson() =>
    RustLib.instance.api.crateApiGetAllGamesJson();

/// Get game content as JSON
Future<String> getGameContentJson(
        {required String gameId, required String biz}) =>
    RustLib.instance.api.crateApiGetGameContentJson(gameId: gameId, biz: biz);

/// Check if a game is installed
bool isGameInstalled({required String gameId, required String biz}) =>
    RustLib.instance.api.crateApiIsGameInstalled(gameId: gameId, biz: biz);

/// Get download progress as JSON (returns "null" if no download in progress)
String getDownloadProgressJson({required String gameId}) =>
    RustLib.instance.api.crateApiGetDownloadProgressJson(gameId: gameId);

/// Get data directory path
String getDataPath() => RustLib.instance.api.crateApiGetDataPath();

/// Get config file path
String getConfigPath() => RustLib.instance.api.crateApiGetConfigPath();

/// Install/download a game
/// Returns "ok" if installation started, or an error message
Future<String> installGame({required String gameId, required String biz}) =>
    RustLib.instance.api.crateApiInstallGame(gameId: gameId, biz: biz);

/// Launch an installed game
/// Returns "ok" if launch started, or an error message
Future<String> launchGame({required String gameId}) =>
    RustLib.instance.api.crateApiLaunchGame(gameId: gameId);

/// Get available runners as JSON
String getAvailableRunnersJson() =>
    RustLib.instance.api.crateApiGetAvailableRunnersJson();

/// Get available components (umu-launcher, jadeite) as JSON
String getAvailableComponentsJson() =>
    RustLib.instance.api.crateApiGetAvailableComponentsJson();

/// Install a runner by name
/// Returns "ok" if installation succeeded, or an error message
Future<String> installRunner({required String runnerName}) =>
    RustLib.instance.api.crateApiInstallRunner(runnerName: runnerName);

/// Delete a runner by name
/// Returns "ok" if deletion succeeded, or an error message
Future<String> deleteRunner({required String runnerName}) =>
    RustLib.instance.api.crateApiDeleteRunner(runnerName: runnerName);

/// Install UMU launcher component
/// Returns "ok" if installation succeeded, or an error message
Future<String> installUmuLauncher() =>
    RustLib.instance.api.crateApiInstallUmuLauncher();

/// Install Jadeite component
/// Returns "ok" if installation succeeded, or an error message
Future<String> installJadeite() =>
    RustLib.instance.api.crateApiInstallJadeite();

/// Delete UMU launcher component
/// Returns "ok" if deletion succeeded, or an error message
Future<String> deleteUmuLauncher() =>
    RustLib.instance.api.crateApiDeleteUmuLauncher();

/// Delete Jadeite component
/// Returns "ok" if deletion succeeded, or an error message
Future<String> deleteJadeite() => RustLib.instance.api.crateApiDeleteJadeite();

/// Start streaming video frames from a URL
/// Streams video frames via the provided sink
Stream<VideoFrameDto> streamVideoFrames({required String url}) =>
    RustLib.instance.api.crateApiStreamVideoFrames(url: url);

/// Video frame DTO for FFI
class VideoFrameDto {
  /// RGBA image data
  final Uint8List data;

  /// Image width
  final int width;

  /// Image height
  final int height;

  /// Frame timestamp in milliseconds
  final PlatformInt64 timestampMs;

  const VideoFrameDto({
    required this.data,
    required this.width,
    required this.height,
    required this.timestampMs,
  });

  @override
  int get hashCode =>
      data.hashCode ^ width.hashCode ^ height.hashCode ^ timestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoFrameDto &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          width == other.width &&
          height == other.height &&
          timestampMs == other.timestampMs;
}
