// GENERATED FILE - DO NOT EDIT
// This file is generated by flutter_rust_bridge_codegen
// Run: flutter_rust_bridge_codegen generate
//
// This is a placeholder that will be replaced by actual generated bindings.
// The functions below match the Rust API signatures.

// ignore_for_file: unused_import, unused_field, camel_case_types

import 'dart:async';
import 'dart:ffi' as ffi;
import 'dart:io';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Rust library instance
class RustLib {
  static RustLib? _instance;
  static bool _initialized = false;
  
  static RustLib get instance {
    if (_instance == null) {
      throw StateError('RustLib not initialized. Call RustLib.init() first.');
    }
    return _instance!;
  }
  
  final RustLibApi api;
  final ffi.DynamicLibrary _dylib;
  
  RustLib._(this.api, this._dylib);
  
  /// Initialize the Rust library
  static Future<void> init() async {
    if (_initialized) return;
    
    // Load the native library
    final dylib = _loadLibrary();
    
    // Create the API instance
    final api = RustLibApiImpl(dylib);
    
    _instance = RustLib._(api, dylib);
    _initialized = true;
  }
  
  static ffi.DynamicLibrary _loadLibrary() {
    const libName = 'rust_bridge';
    
    if (Platform.isLinux) {
      // Try different paths for the library
      final paths = [
        'lib$libName.so',
        'lib/lib$libName.so',
        './lib$libName.so',
      ];
      
      for (final path in paths) {
        try {
          return ffi.DynamicLibrary.open(path);
        } catch (_) {
          continue;
        }
      }
      
      // Last resort - let the system find it
      return ffi.DynamicLibrary.open('lib$libName.so');
    } else if (Platform.isMacOS) {
      return ffi.DynamicLibrary.open('lib$libName.dylib');
    } else if (Platform.isWindows) {
      return ffi.DynamicLibrary.open('$libName.dll');
    }
    
    throw UnsupportedError('Unsupported platform: ${Platform.operatingSystem}');
  }
}

/// API interface for Rust functions
abstract class RustLibApi {
  String initBackend();
  String getSettingsJson();
  Future<String> getAllGamesJson();
  Future<String> getGameContentJson({required String gameId, required String biz});
  bool isGameInstalled({required String gameId, required String biz});
  String getDownloadProgressJson({required String gameId});
  String getDataPath();
  String getConfigPath();
}

/// Placeholder API implementation
/// This will be replaced by the actual generated implementation from flutter_rust_bridge_codegen
class RustLibApiImpl implements RustLibApi {
  final ffi.DynamicLibrary _dylib;
  
  RustLibApiImpl(this._dylib) {
    // The dylib will be used by the real codegen implementation
    // This placeholder just stores the reference
  }
  
  @override
  String initBackend() {
    // Placeholder - will be implemented by codegen
    throw UnimplementedError('FFI bindings not generated. Run flutter_rust_bridge_codegen generate');
  }
  
  @override
  String getSettingsJson() {
    throw UnimplementedError('FFI bindings not generated. Run flutter_rust_bridge_codegen generate');
  }
  
  @override
  Future<String> getAllGamesJson() async {
    throw UnimplementedError('FFI bindings not generated. Run flutter_rust_bridge_codegen generate');
  }
  
  @override
  Future<String> getGameContentJson({required String gameId, required String biz}) async {
    throw UnimplementedError('FFI bindings not generated. Run flutter_rust_bridge_codegen generate');
  }
  
  @override
  bool isGameInstalled({required String gameId, required String biz}) {
    throw UnimplementedError('FFI bindings not generated. Run flutter_rust_bridge_codegen generate');
  }
  
  @override
  String getDownloadProgressJson({required String gameId}) {
    throw UnimplementedError('FFI bindings not generated. Run flutter_rust_bridge_codegen generate');
  }
  
  @override
  String getDataPath() {
    throw UnimplementedError('FFI bindings not generated. Run flutter_rust_bridge_codegen generate');
  }
  
  @override
  String getConfigPath() {
    throw UnimplementedError('FFI bindings not generated. Run flutter_rust_bridge_codegen generate');
  }
}

// Global function wrappers that call through RustLib.instance.api
String initBackend() => RustLib.instance.api.initBackend();
String getSettingsJson() => RustLib.instance.api.getSettingsJson();
Future<String> getAllGamesJson() => RustLib.instance.api.getAllGamesJson();
Future<String> getGameContentJson({required String gameId, required String biz}) => 
    RustLib.instance.api.getGameContentJson(gameId: gameId, biz: biz);
bool isGameInstalledSync({required String gameId, required String biz}) => 
    RustLib.instance.api.isGameInstalled(gameId: gameId, biz: biz);
String getDownloadProgressJson({required String gameId}) => 
    RustLib.instance.api.getDownloadProgressJson(gameId: gameId);
String getDataPath() => RustLib.instance.api.getDataPath();
String getConfigPath() => RustLib.instance.api.getConfigPath();
