// AUTO-GENERATED FILE - DO NOT EDIT
// This file is generated by flutter_rust_bridge_codegen
// Run: flutter_rust_bridge_codegen generate
//
// This is a placeholder file that will be replaced by the actual generated bindings
// when flutter_rust_bridge_codegen is run during the build process.

// ignore_for_file: unused_import, unused_field

import 'dart:async';
import 'dart:ffi' as ffi;

/// Rust library instance
class RustLib {
  static RustLib? _instance;
  
  static RustLib get instance {
    if (_instance == null) {
      throw StateError('RustLib not initialized. Call RustLib.init() first.');
    }
    return _instance!;
  }
  
  final RustLibApi api;
  
  RustLib._(this.api);
  
  /// Initialize the Rust library
  static Future<void> init() async {
    if (_instance != null) return;
    
    // Load the native library
    final dylib = _loadLibrary();
    
    // Create the API instance
    final api = RustLibApiImpl(dylib);
    
    _instance = RustLib._(api);
  }
  
  static ffi.DynamicLibrary _loadLibrary() {
    const libName = 'rust_bridge';
    
    if (ffi.Abi.current() == ffi.Abi.linuxX64) {
      return ffi.DynamicLibrary.open('lib$libName.so');
    } else if (ffi.Abi.current() == ffi.Abi.macosX64 || 
               ffi.Abi.current() == ffi.Abi.macosArm64) {
      return ffi.DynamicLibrary.open('lib$libName.dylib');
    } else if (ffi.Abi.current() == ffi.Abi.windowsX64) {
      return ffi.DynamicLibrary.open('$libName.dll');
    }
    
    throw UnsupportedError('Unsupported platform');
  }
}

/// API interface for Rust functions
abstract class RustLibApi {
  dynamic loadSettings();
  dynamic createDefaultSettings();
  Future<List<dynamic>> getAllGames({required dynamic settings});
  Future<dynamic> getGameContent({
    required dynamic settings,
    required String gameId,
    required String biz,
  });
  bool isGameInstalled({
    required dynamic settings,
    required String gameId,
    required String biz,
  });
  dynamic getDownloadProgress({required String gameId});
  void runGame({required dynamic settings, required String gameId});
}

/// Placeholder API implementation
/// This will be replaced by the actual generated implementation
class RustLibApiImpl implements RustLibApi {
  final ffi.DynamicLibrary _dylib;
  
  RustLibApiImpl(this._dylib);
  
  @override
  dynamic loadSettings() {
    // TODO: Implement via FFI
    throw UnimplementedError('FFI bindings not generated yet');
  }
  
  @override
  dynamic createDefaultSettings() {
    // TODO: Implement via FFI
    throw UnimplementedError('FFI bindings not generated yet');
  }
  
  @override
  Future<List<dynamic>> getAllGames({required dynamic settings}) async {
    // TODO: Implement via FFI
    throw UnimplementedError('FFI bindings not generated yet');
  }
  
  @override
  Future<dynamic> getGameContent({
    required dynamic settings,
    required String gameId,
    required String biz,
  }) async {
    // TODO: Implement via FFI
    throw UnimplementedError('FFI bindings not generated yet');
  }
  
  @override
  bool isGameInstalled({
    required dynamic settings,
    required String gameId,
    required String biz,
  }) {
    // TODO: Implement via FFI
    throw UnimplementedError('FFI bindings not generated yet');
  }
  
  @override
  dynamic getDownloadProgress({required String gameId}) {
    // TODO: Implement via FFI
    throw UnimplementedError('FFI bindings not generated yet');
  }
  
  @override
  void runGame({required dynamic settings, required String gameId}) {
    // TODO: Implement via FFI
    throw UnimplementedError('FFI bindings not generated yet');
  }
}
