// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  String cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_strict(Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void wire__crate__api__delete_jadeite(NativePortType port_) =>
      wasmModule.wire__crate__api__delete_jadeite(port_);

  void wire__crate__api__delete_runner(
          NativePortType port_, String runner_name) =>
      wasmModule.wire__crate__api__delete_runner(port_, runner_name);

  void wire__crate__api__delete_umu_launcher(NativePortType port_) =>
      wasmModule.wire__crate__api__delete_umu_launcher(port_);

  void wire__crate__api__get_all_games_json(NativePortType port_) =>
      wasmModule.wire__crate__api__get_all_games_json(port_);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__get_available_components_json() =>
          wasmModule.wire__crate__api__get_available_components_json();

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__get_available_runners_json() =>
          wasmModule.wire__crate__api__get_available_runners_json();

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__get_config_path() =>
          wasmModule.wire__crate__api__get_config_path();

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__get_data_path() =>
          wasmModule.wire__crate__api__get_data_path();

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__get_download_progress_json(String game_id) =>
          wasmModule.wire__crate__api__get_download_progress_json(game_id);

  void wire__crate__api__get_game_content_json(
          NativePortType port_, String game_id, String biz) =>
      wasmModule.wire__crate__api__get_game_content_json(port_, game_id, biz);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__get_settings_json() =>
          wasmModule.wire__crate__api__get_settings_json();

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__init_backend() =>
          wasmModule.wire__crate__api__init_backend();

  void wire__crate__api__install_game(
          NativePortType port_, String game_id, String biz) =>
      wasmModule.wire__crate__api__install_game(port_, game_id, biz);

  void wire__crate__api__install_jadeite(NativePortType port_) =>
      wasmModule.wire__crate__api__install_jadeite(port_);

  void wire__crate__api__install_runner(
          NativePortType port_, String runner_name) =>
      wasmModule.wire__crate__api__install_runner(port_, runner_name);

  void wire__crate__api__install_umu_launcher(NativePortType port_) =>
      wasmModule.wire__crate__api__install_umu_launcher(port_);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__is_game_installed(String game_id, String biz) =>
          wasmModule.wire__crate__api__is_game_installed(game_id, biz);

  void wire__crate__api__launch_game(NativePortType port_, String game_id) =>
      wasmModule.wire__crate__api__launch_game(port_, game_id);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void wire__crate__api__delete_jadeite(NativePortType port_);

  external void wire__crate__api__delete_runner(
      NativePortType port_, String runner_name);

  external void wire__crate__api__delete_umu_launcher(NativePortType port_);

  external void wire__crate__api__get_all_games_json(NativePortType port_);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__get_available_components_json();

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__get_available_runners_json();

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__get_config_path();

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__get_data_path();

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__get_download_progress_json(String game_id);

  external void wire__crate__api__get_game_content_json(
      NativePortType port_, String game_id, String biz);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__get_settings_json();

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__init_backend();

  external void wire__crate__api__install_game(
      NativePortType port_, String game_id, String biz);

  external void wire__crate__api__install_jadeite(NativePortType port_);

  external void wire__crate__api__install_runner(
      NativePortType port_, String runner_name);

  external void wire__crate__api__install_umu_launcher(NativePortType port_);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__is_game_installed(String game_id, String biz);

  external void wire__crate__api__launch_game(
      NativePortType port_, String game_id);
}
