// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<VideoFrameDto> dco_decode_StreamSink_video_frame_dto_Dco(
      dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VideoFrameDto dco_decode_video_frame_dto(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<VideoFrameDto> sse_decode_StreamSink_video_frame_dto_Dco(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VideoFrameDto sse_decode_video_frame_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_AnyhowException(
      AnyhowException raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict>
      cst_encode_StreamSink_video_frame_dto_Dco(
          RustStreamSink<VideoFrameDto> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_String(raw.setupAndSerialize(
        codec: DcoCodec(
      decodeSuccessData: dco_decode_video_frame_dto,
      decodeErrorData: dco_decode_AnyhowException,
    )));
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  int cst_encode_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toInt();
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(
      Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  void cst_api_fill_to_wire_video_frame_dto(
      VideoFrameDto apiObj, wire_cst_video_frame_dto wireObj) {
    wireObj.data = cst_encode_list_prim_u_8_strict(apiObj.data);
    wireObj.width = cst_encode_u_32(apiObj.width);
    wireObj.height = cst_encode_u_32(apiObj.height);
    wireObj.timestamp_ms = cst_encode_i_64(apiObj.timestampMs);
  }

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_video_frame_dto_Dco(
      RustStreamSink<VideoFrameDto> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_video_frame_dto(VideoFrameDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// generated by flutter_rust_bridge
class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustLibWire.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void store_dart_post_cobject(
    DartPostCObjectFnType ptr,
  ) {
    return _store_dart_post_cobject(
      ptr,
    );
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
          'store_dart_post_cobject');
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  void wire__crate__api__delete_jadeite(
    int port_,
  ) {
    return _wire__crate__api__delete_jadeite(
      port_,
    );
  }

  late final _wire__crate__api__delete_jadeitePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'frbgen_elysia_wire__crate__api__delete_jadeite');
  late final _wire__crate__api__delete_jadeite =
      _wire__crate__api__delete_jadeitePtr.asFunction<void Function(int)>();

  void wire__crate__api__delete_runner(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> runner_name,
  ) {
    return _wire__crate__api__delete_runner(
      port_,
      runner_name,
    );
  }

  late final _wire__crate__api__delete_runnerPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_elysia_wire__crate__api__delete_runner');
  late final _wire__crate__api__delete_runner =
      _wire__crate__api__delete_runnerPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__delete_umu_launcher(
    int port_,
  ) {
    return _wire__crate__api__delete_umu_launcher(
      port_,
    );
  }

  late final _wire__crate__api__delete_umu_launcherPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'frbgen_elysia_wire__crate__api__delete_umu_launcher');
  late final _wire__crate__api__delete_umu_launcher =
      _wire__crate__api__delete_umu_launcherPtr
          .asFunction<void Function(int)>();

  void wire__crate__api__get_all_games_json(
    int port_,
  ) {
    return _wire__crate__api__get_all_games_json(
      port_,
    );
  }

  late final _wire__crate__api__get_all_games_jsonPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'frbgen_elysia_wire__crate__api__get_all_games_json');
  late final _wire__crate__api__get_all_games_json =
      _wire__crate__api__get_all_games_jsonPtr.asFunction<void Function(int)>();

  WireSyncRust2DartDco wire__crate__api__get_available_components_json() {
    return _wire__crate__api__get_available_components_json();
  }

  late final _wire__crate__api__get_available_components_jsonPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
          'frbgen_elysia_wire__crate__api__get_available_components_json');
  late final _wire__crate__api__get_available_components_json =
      _wire__crate__api__get_available_components_jsonPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__get_available_runners_json() {
    return _wire__crate__api__get_available_runners_json();
  }

  late final _wire__crate__api__get_available_runners_jsonPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
          'frbgen_elysia_wire__crate__api__get_available_runners_json');
  late final _wire__crate__api__get_available_runners_json =
      _wire__crate__api__get_available_runners_jsonPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__get_config_path() {
    return _wire__crate__api__get_config_path();
  }

  late final _wire__crate__api__get_config_pathPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
          'frbgen_elysia_wire__crate__api__get_config_path');
  late final _wire__crate__api__get_config_path =
      _wire__crate__api__get_config_pathPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__get_data_path() {
    return _wire__crate__api__get_data_path();
  }

  late final _wire__crate__api__get_data_pathPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
          'frbgen_elysia_wire__crate__api__get_data_path');
  late final _wire__crate__api__get_data_path =
      _wire__crate__api__get_data_pathPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__get_download_progress_json(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> game_id,
  ) {
    return _wire__crate__api__get_download_progress_json(
      game_id,
    );
  }

  late final _wire__crate__api__get_download_progress_jsonPtr = _lookup<
          ffi.NativeFunction<
              WireSyncRust2DartDco Function(
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_elysia_wire__crate__api__get_download_progress_json');
  late final _wire__crate__api__get_download_progress_json =
      _wire__crate__api__get_download_progress_jsonPtr.asFunction<
          WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__get_game_content_json(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> game_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> biz,
  ) {
    return _wire__crate__api__get_game_content_json(
      port_,
      game_id,
      biz,
    );
  }

  late final _wire__crate__api__get_game_content_jsonPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_elysia_wire__crate__api__get_game_content_json');
  late final _wire__crate__api__get_game_content_json =
      _wire__crate__api__get_game_content_jsonPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  WireSyncRust2DartDco wire__crate__api__get_settings_json() {
    return _wire__crate__api__get_settings_json();
  }

  late final _wire__crate__api__get_settings_jsonPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
          'frbgen_elysia_wire__crate__api__get_settings_json');
  late final _wire__crate__api__get_settings_json =
      _wire__crate__api__get_settings_jsonPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__init_backend() {
    return _wire__crate__api__init_backend();
  }

  late final _wire__crate__api__init_backendPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
          'frbgen_elysia_wire__crate__api__init_backend');
  late final _wire__crate__api__init_backend =
      _wire__crate__api__init_backendPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  void wire__crate__api__install_game(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> game_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> biz,
  ) {
    return _wire__crate__api__install_game(
      port_,
      game_id,
      biz,
    );
  }

  late final _wire__crate__api__install_gamePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_elysia_wire__crate__api__install_game');
  late final _wire__crate__api__install_game =
      _wire__crate__api__install_gamePtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__install_jadeite(
    int port_,
  ) {
    return _wire__crate__api__install_jadeite(
      port_,
    );
  }

  late final _wire__crate__api__install_jadeitePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'frbgen_elysia_wire__crate__api__install_jadeite');
  late final _wire__crate__api__install_jadeite =
      _wire__crate__api__install_jadeitePtr.asFunction<void Function(int)>();

  void wire__crate__api__install_runner(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> runner_name,
  ) {
    return _wire__crate__api__install_runner(
      port_,
      runner_name,
    );
  }

  late final _wire__crate__api__install_runnerPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_elysia_wire__crate__api__install_runner');
  late final _wire__crate__api__install_runner =
      _wire__crate__api__install_runnerPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__install_umu_launcher(
    int port_,
  ) {
    return _wire__crate__api__install_umu_launcher(
      port_,
    );
  }

  late final _wire__crate__api__install_umu_launcherPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'frbgen_elysia_wire__crate__api__install_umu_launcher');
  late final _wire__crate__api__install_umu_launcher =
      _wire__crate__api__install_umu_launcherPtr
          .asFunction<void Function(int)>();

  WireSyncRust2DartDco wire__crate__api__is_game_installed(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> game_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> biz,
  ) {
    return _wire__crate__api__is_game_installed(
      game_id,
      biz,
    );
  }

  late final _wire__crate__api__is_game_installedPtr = _lookup<
          ffi.NativeFunction<
              WireSyncRust2DartDco Function(
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_elysia_wire__crate__api__is_game_installed');
  late final _wire__crate__api__is_game_installed =
      _wire__crate__api__is_game_installedPtr.asFunction<
          WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__launch_game(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> game_id,
  ) {
    return _wire__crate__api__launch_game(
      port_,
      game_id,
    );
  }

  late final _wire__crate__api__launch_gamePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_elysia_wire__crate__api__launch_game');
  late final _wire__crate__api__launch_game =
      _wire__crate__api__launch_gamePtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__stream_video_frames(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> url,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> sink,
  ) {
    return _wire__crate__api__stream_video_frames(
      port_,
      url,
      sink,
    );
  }

  late final _wire__crate__api__stream_video_framesPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_elysia_wire__crate__api__stream_video_frames');
  late final _wire__crate__api__stream_video_frames =
      _wire__crate__api__stream_video_framesPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_8_strict(
      len,
    );
  }

  late final _cst_new_list_prim_u_8_strictPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(
              ffi.Int32)>>('frbgen_elysia_cst_new_list_prim_u_8_strict');
  late final _cst_new_list_prim_u_8_strict = _cst_new_list_prim_u_8_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
          'dummy_method_to_enforce_bundling');
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();
}

typedef DartPostCObjectFnType
    = ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnTypeFunction>>;
typedef DartPostCObjectFnTypeFunction = ffi.Bool Function(
    DartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartDartPostCObjectFnTypeFunction = bool Function(
    DartDartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartPort = ffi.Int64;
typedef DartDartPort = int;

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_video_frame_dto extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> data;

  @ffi.Uint32()
  external int width;

  @ffi.Uint32()
  external int height;

  @ffi.Int64()
  external int timestamp_ms;
}
