// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1604030145;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_bridge',
    ioDirectory: '../rust_bridge/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiDeleteJadeite();

  Future<String> crateApiDeleteRunner({required String runnerName});

  Future<String> crateApiDeleteUmuLauncher();

  Future<String> crateApiGetAllGamesJson();

  String crateApiGetAvailableComponentsJson();

  String crateApiGetAvailableRunnersJson();

  String crateApiGetConfigPath();

  String crateApiGetDataPath();

  String crateApiGetDownloadProgressJson({required String gameId});

  Future<String> crateApiGetGameContentJson(
      {required String gameId, required String biz});

  String crateApiGetSettingsJson();

  String crateApiInitBackend();

  Future<String> crateApiInstallGame(
      {required String gameId, required String biz});

  Future<String> crateApiInstallJadeite();

  Future<String> crateApiInstallRunner({required String runnerName});

  Future<String> crateApiInstallUmuLauncher();

  bool crateApiIsGameInstalled({required String gameId, required String biz});

  Future<String> crateApiLaunchGame({required String gameId});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiDeleteJadeite() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__api__delete_jadeite(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDeleteJadeiteConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDeleteJadeiteConstMeta => const TaskConstMeta(
        debugName: "delete_jadeite",
        argNames: [],
      );

  @override
  Future<String> crateApiDeleteRunner({required String runnerName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_String(runnerName);
        return wire.wire__crate__api__delete_runner(port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDeleteRunnerConstMeta,
      argValues: [runnerName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDeleteRunnerConstMeta => const TaskConstMeta(
        debugName: "delete_runner",
        argNames: ["runnerName"],
      );

  @override
  Future<String> crateApiDeleteUmuLauncher() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__api__delete_umu_launcher(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDeleteUmuLauncherConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDeleteUmuLauncherConstMeta => const TaskConstMeta(
        debugName: "delete_umu_launcher",
        argNames: [],
      );

  @override
  Future<String> crateApiGetAllGamesJson() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__api__get_all_games_json(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetAllGamesJsonConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetAllGamesJsonConstMeta => const TaskConstMeta(
        debugName: "get_all_games_json",
        argNames: [],
      );

  @override
  String crateApiGetAvailableComponentsJson() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        return wire.wire__crate__api__get_available_components_json();
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetAvailableComponentsJsonConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetAvailableComponentsJsonConstMeta =>
      const TaskConstMeta(
        debugName: "get_available_components_json",
        argNames: [],
      );

  @override
  String crateApiGetAvailableRunnersJson() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        return wire.wire__crate__api__get_available_runners_json();
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetAvailableRunnersJsonConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetAvailableRunnersJsonConstMeta =>
      const TaskConstMeta(
        debugName: "get_available_runners_json",
        argNames: [],
      );

  @override
  String crateApiGetConfigPath() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        return wire.wire__crate__api__get_config_path();
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetConfigPathConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetConfigPathConstMeta => const TaskConstMeta(
        debugName: "get_config_path",
        argNames: [],
      );

  @override
  String crateApiGetDataPath() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        return wire.wire__crate__api__get_data_path();
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetDataPathConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetDataPathConstMeta => const TaskConstMeta(
        debugName: "get_data_path",
        argNames: [],
      );

  @override
  String crateApiGetDownloadProgressJson({required String gameId}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        var arg0 = cst_encode_String(gameId);
        return wire.wire__crate__api__get_download_progress_json(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetDownloadProgressJsonConstMeta,
      argValues: [gameId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetDownloadProgressJsonConstMeta =>
      const TaskConstMeta(
        debugName: "get_download_progress_json",
        argNames: ["gameId"],
      );

  @override
  Future<String> crateApiGetGameContentJson(
      {required String gameId, required String biz}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_String(gameId);
        var arg1 = cst_encode_String(biz);
        return wire.wire__crate__api__get_game_content_json(port_, arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetGameContentJsonConstMeta,
      argValues: [gameId, biz],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetGameContentJsonConstMeta => const TaskConstMeta(
        debugName: "get_game_content_json",
        argNames: ["gameId", "biz"],
      );

  @override
  String crateApiGetSettingsJson() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        return wire.wire__crate__api__get_settings_json();
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGetSettingsJsonConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetSettingsJsonConstMeta => const TaskConstMeta(
        debugName: "get_settings_json",
        argNames: [],
      );

  @override
  String crateApiInitBackend() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        return wire.wire__crate__api__init_backend();
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiInitBackendConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitBackendConstMeta => const TaskConstMeta(
        debugName: "init_backend",
        argNames: [],
      );

  @override
  Future<String> crateApiInstallGame(
      {required String gameId, required String biz}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_String(gameId);
        var arg1 = cst_encode_String(biz);
        return wire.wire__crate__api__install_game(port_, arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiInstallGameConstMeta,
      argValues: [gameId, biz],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInstallGameConstMeta => const TaskConstMeta(
        debugName: "install_game",
        argNames: ["gameId", "biz"],
      );

  @override
  Future<String> crateApiInstallJadeite() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__api__install_jadeite(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiInstallJadeiteConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInstallJadeiteConstMeta => const TaskConstMeta(
        debugName: "install_jadeite",
        argNames: [],
      );

  @override
  Future<String> crateApiInstallRunner({required String runnerName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_String(runnerName);
        return wire.wire__crate__api__install_runner(port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiInstallRunnerConstMeta,
      argValues: [runnerName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInstallRunnerConstMeta => const TaskConstMeta(
        debugName: "install_runner",
        argNames: ["runnerName"],
      );

  @override
  Future<String> crateApiInstallUmuLauncher() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__api__install_umu_launcher(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiInstallUmuLauncherConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInstallUmuLauncherConstMeta => const TaskConstMeta(
        debugName: "install_umu_launcher",
        argNames: [],
      );

  @override
  bool crateApiIsGameInstalled({required String gameId, required String biz}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        var arg0 = cst_encode_String(gameId);
        var arg1 = cst_encode_String(biz);
        return wire.wire__crate__api__is_game_installed(arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiIsGameInstalledConstMeta,
      argValues: [gameId, biz],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiIsGameInstalledConstMeta => const TaskConstMeta(
        debugName: "is_game_installed",
        argNames: ["gameId", "biz"],
      );

  @override
  Future<String> crateApiLaunchGame({required String gameId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_String(gameId);
        return wire.wire__crate__api__launch_game(port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLaunchGameConstMeta,
      argValues: [gameId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLaunchGameConstMeta => const TaskConstMeta(
        debugName: "launch_game",
        argNames: ["gameId"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool cst_encode_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_u_8(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void cst_encode_unit(void raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
