// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A runner that can be downloaded and installed
class AvailableRunner {
  final String name;
  final String displayName;
  final RunnerType runnerType;
  final String version;
  final String downloadUrl;

  /// The folder name to use when extracting (stripped of top-level directory)
  final String folderName;

  const AvailableRunner({
    required this.name,
    required this.displayName,
    required this.runnerType,
    required this.version,
    required this.downloadUrl,
    required this.folderName,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      displayName.hashCode ^
      runnerType.hashCode ^
      version.hashCode ^
      downloadUrl.hashCode ^
      folderName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AvailableRunner &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          displayName == other.displayName &&
          runnerType == other.runnerType &&
          version == other.version &&
          downloadUrl == other.downloadUrl &&
          folderName == other.folderName;
}

/// Available runner types
enum RunnerType {
  wine,
  proton,
  ;
}
