// Real Rust backend service using flutter_rust_bridge
// This service calls into the Rust backend via FFI

import 'package:flutter/foundation.dart';
import '../models/models.dart';
import 'backend_service.dart';

// Import the generated FFI bindings
// These are generated by flutter_rust_bridge_codegen
import '../rust/frb_generated.dart';

/// Rust backend service implementation
class RustBackendService implements BackendService {
  bool _initialized = false;
  
  /// Initialize the Rust backend
  @override
  Future<void> initialize() async {
    if (_initialized) return;
    
    try {
      debugPrint('[RustBackend] Initializing Rust backend...');
      await RustLib.init();
      _initialized = true;
      debugPrint('[RustBackend] Rust backend initialized successfully');
    } catch (e) {
      debugPrint('[RustBackend] Failed to initialize: $e');
      rethrow;
    }
  }
  
  /// Get list of all games from Rust backend
  @override
  Future<List<Game>> getGames() async {
    await _ensureInitialized();
    
    try {
      debugPrint('[RustBackend] Fetching games...');
      
      // Get or create settings
      final settings = await _getSettings();
      
      // Call Rust API to get all games
      final rustGames = await api.getAllGames(settings: settings);
      
      // Convert Rust types to Dart types
      final games = rustGames.map((g) => _convertGame(g)).toList();
      
      debugPrint('[RustBackend] Fetched ${games.length} games');
      return games;
    } catch (e) {
      debugPrint('[RustBackend] Error fetching games: $e');
      rethrow;
    }
  }
  
  /// Get game content (banners, news, etc.)
  @override
  Future<Content?> getGameContent(String gameId, String biz) async {
    await _ensureInitialized();
    
    try {
      debugPrint('[RustBackend] Fetching content for game: $gameId');
      
      final settings = await _getSettings();
      final rustContent = await api.getGameContent(
        settings: settings,
        gameId: gameId,
        biz: biz,
      );
      
      return _convertContent(rustContent);
    } catch (e) {
      debugPrint('[RustBackend] Error fetching game content: $e');
      return null;
    }
  }
  
  /// Check if a game is installed
  @override
  bool isGameInstalled(String gameId, String biz) {
    if (!_initialized) return false;
    
    try {
      final settings = api.loadSettings();
      return api.isGameInstalled(
        settings: settings,
        gameId: gameId,
        biz: biz,
      );
    } catch (e) {
      debugPrint('[RustBackend] Error checking installation: $e');
      return false;
    }
  }
  
  /// Get download progress for a game
  @override
  DownloadProgress? getDownloadProgress(String gameId) {
    if (!_initialized) return null;
    
    try {
      final rustProgress = api.getDownloadProgress(gameId: gameId);
      if (rustProgress == null) return null;
      
      return DownloadProgress(
        downloaded: rustProgress.downloaded,
        total: rustProgress.total,
        mbPerSecond: rustProgress.mbPerSecond,
        partIndex: rustProgress.partIndex,
        partsTotal: rustProgress.partsTotal,
        status: rustProgress.status,
        isBusy: rustProgress.isBusy,
      );
    } catch (e) {
      debugPrint('[RustBackend] Error getting download progress: $e');
      return null;
    }
  }
  
  /// Install/download a game
  @override
  Future<void> installGame(String gameId, String biz) async {
    await _ensureInitialized();
    
    debugPrint('[RustBackend] Installing game: $gameId');
    // TODO: Implement game installation via Rust backend
    // This will need to call the installer API
  }
  
  /// Launch an installed game
  @override
  Future<void> launchGame(String gameId) async {
    await _ensureInitialized();
    
    try {
      debugPrint('[RustBackend] Launching game: $gameId');
      final settings = api.loadSettings();
      api.runGame(settings: settings, gameId: gameId);
    } catch (e) {
      debugPrint('[RustBackend] Error launching game: $e');
      rethrow;
    }
  }
  
  /// Ensure the backend is initialized
  Future<void> _ensureInitialized() async {
    if (!_initialized) {
      await initialize();
    }
  }
  
  /// Get or create settings
  Future<dynamic> _getSettings() async {
    try {
      return api.loadSettings();
    } catch (e) {
      debugPrint('[RustBackend] Creating default settings');
      return api.createDefaultSettings();
    }
  }
  
  /// Convert Rust Game to Dart Game model
  Game _convertGame(dynamic rustGame) {
    return Game(
      id: rustGame.id,
      biz: rustGame.biz,
      display: Display(
        language: rustGame.display.language,
        name: rustGame.display.name,
        icon: Image(
          url: rustGame.display.icon.url,
          hoverUrl: rustGame.display.icon.hoverUrl,
          link: rustGame.display.icon.link,
          md5: rustGame.display.icon.md5,
          size: rustGame.display.icon.size,
        ),
        title: rustGame.display.title,
        subtitle: rustGame.display.subtitle,
        background: ImageLink(
          url: rustGame.display.background.url,
          link: rustGame.display.background.link,
        ),
        logo: ImageLink(
          url: rustGame.display.logo.url,
          link: rustGame.display.logo.link,
        ),
        thumbnail: ImageLink(
          url: rustGame.display.thumbnail.url,
          link: rustGame.display.thumbnail.link,
        ),
        shortcut: Image(
          url: rustGame.display.shortcut.url,
          hoverUrl: rustGame.display.shortcut.hoverUrl,
          link: rustGame.display.shortcut.link,
          md5: rustGame.display.shortcut.md5,
          size: rustGame.display.shortcut.size,
        ),
      ),
      displayStatus: rustGame.displayStatus,
    );
  }
  
  /// Convert Rust Content to Dart Content model
  Content _convertContent(dynamic rustContent) {
    return Content(
      game: GameInfo(
        id: rustContent.game.id,
        biz: rustContent.game.biz,
      ),
      language: rustContent.language,
      banners: (rustContent.banners as List).map((b) => Banner(
        id: b.id,
        image: ImageLink(url: b.image.url, link: b.image.link),
        i18nIdentifier: b.i18nIdentifier,
      )).toList(),
      posts: (rustContent.posts as List).map((p) => Post(
        id: p.id,
        postType: p.postType,
        title: p.title,
        link: p.link,
        date: p.date,
      )).toList(),
      socialMediaList: (rustContent.socialMediaList as List).map((s) => SocialMedia(
        id: s.id,
        icon: Image(
          url: s.icon.url,
          hoverUrl: s.icon.hoverUrl,
          link: s.icon.link,
          md5: s.icon.md5,
          size: s.icon.size,
        ),
        qrDesc: s.qrDesc,
      )).toList(),
    );
  }
}

/// API accessor for the generated Rust bindings
/// This is a placeholder that will be replaced by the generated code
class api {
  static dynamic loadSettings() {
    return RustLib.instance.api.loadSettings();
  }
  
  static dynamic createDefaultSettings() {
    return RustLib.instance.api.createDefaultSettings();
  }
  
  static Future<List<dynamic>> getAllGames({required dynamic settings}) {
    return RustLib.instance.api.getAllGames(settings: settings);
  }
  
  static Future<dynamic> getGameContent({
    required dynamic settings,
    required String gameId,
    required String biz,
  }) {
    return RustLib.instance.api.getGameContent(
      settings: settings,
      gameId: gameId,
      biz: biz,
    );
  }
  
  static bool isGameInstalled({
    required dynamic settings,
    required String gameId,
    required String biz,
  }) {
    return RustLib.instance.api.isGameInstalled(
      settings: settings,
      gameId: gameId,
      biz: biz,
    );
  }
  
  static dynamic getDownloadProgress({required String gameId}) {
    return RustLib.instance.api.getDownloadProgress(gameId: gameId);
  }
  
  static void runGame({required dynamic settings, required String gameId}) {
    RustLib.instance.api.runGame(settings: settings, gameId: gameId);
  }
}

// ignore_for_file: camel_case_types
