// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Game>>
abstract class Game implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SocialMedia>>
abstract class SocialMedia implements RustOpaqueInterface {}

class Banner {
  final String id;
  final ImageLink image;
  final String i18NIdentifier;

  const Banner({
    required this.id,
    required this.image,
    required this.i18NIdentifier,
  });

  @override
  int get hashCode => id.hashCode ^ image.hashCode ^ i18NIdentifier.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Banner &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          image == other.image &&
          i18NIdentifier == other.i18NIdentifier;
}

class Content {
  final GameInfo game;
  final String language;
  final List<Banner> banners;
  final List<Post> posts;
  final List<SocialMedia> socialMediaList;

  const Content({
    required this.game,
    required this.language,
    required this.banners,
    required this.posts,
    required this.socialMediaList,
  });

  @override
  int get hashCode =>
      game.hashCode ^
      language.hashCode ^
      banners.hashCode ^
      posts.hashCode ^
      socialMediaList.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Content &&
          runtimeType == other.runtimeType &&
          game == other.game &&
          language == other.language &&
          banners == other.banners &&
          posts == other.posts &&
          socialMediaList == other.socialMediaList;
}

class GameInfo {
  final String id;
  final String biz;

  const GameInfo({
    required this.id,
    required this.biz,
  });

  @override
  int get hashCode => id.hashCode ^ biz.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GameInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          biz == other.biz;
}

class ImageLink {
  final String url;
  final String link;
  final bool loginStateInLink;

  const ImageLink({
    required this.url,
    required this.link,
    required this.loginStateInLink,
  });

  @override
  int get hashCode => url.hashCode ^ link.hashCode ^ loginStateInLink.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageLink &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          link == other.link &&
          loginStateInLink == other.loginStateInLink;
}

class Post {
  final String id;
  final String postType;
  final String title;
  final String link;
  final String date;
  final bool loginStateInLink;
  final String i18NIdentifier;

  const Post({
    required this.id,
    required this.postType,
    required this.title,
    required this.link,
    required this.date,
    required this.loginStateInLink,
    required this.i18NIdentifier,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      postType.hashCode ^
      title.hashCode ^
      link.hashCode ^
      date.hashCode ^
      loginStateInLink.hashCode ^
      i18NIdentifier.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Post &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          postType == other.postType &&
          title == other.title &&
          link == other.link &&
          date == other.date &&
          loginStateInLink == other.loginStateInLink &&
          i18NIdentifier == other.i18NIdentifier;
}
